data:
  train_urls:
    - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_train.{1..128}-of-128.jsonl.gz"
  validation_urls:
    - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_val.{1..8}-of-8.jsonl.gz"
  cache_dir: "gs://levanter-data/tokenized/openwebtext_llama/"
  tokenizer: "NousResearch/Llama-2-7b-hf"
model:
  type: llama
  hidden_dim: 32
  num_heads: 4
  num_kv_heads: 4
  num_layers: 2
trainer:
  tracker:
    project: "levanter"
    tags: ["openwebtext", "llama"]
  mp: p=f32
  train_batch_size: 32
  num_train_steps: 100
  steps_per_eval: 50
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
